apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: shopscale
  labels:
    app: payment-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: itsmeynr/payment-service:latest
          ports:
            - containerPort: 4003
          livenessProbe:
            httpGet:
              path: /health
              port: 4003
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 4003
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
